insert into RiskCategory values ('Travel','Putno osiguranje')
insert into RiskCategory values ('Home','Stambeno osiguranje')
insert into RiskCategory values ('Vehicle','Osiguranje vozila')
insert into Risk values ('Duration','Trajanje osiguranja',1)
insert into Risk values ('Region','Region',1)
insert into Risk values ('Person number','Broj osoba',1)
insert into Risk values ('Age','Starost',1)
insert into Risk values ('Sport','Sport',1)
insert into Risk values ('InsuredValue','Osigurana vrednost',1)
insert into Risk values ('FlatArea','Povrsina stana',2)
insert into Risk values ('FlatAge','Starost stana',2)
insert into Risk values ('EstimatedValues','Procenjene vrednosti',2)
insert into Risk values ('InsuredBy','Osigurano od',2)
insert into Risk values ('Packages','Paketi',3)
insert into RiskItem values ('Europe','Evropa',2)
insert into RiskItem values ('Asia','Azija',2)
insert into RiskItem values ('Africa','Afrika',2)
insert into RiskItem values ('South America','Juzna Amerika',2)
insert into RiskItem values ('North America','Severna Amerika',2)
insert into RiskItem values ('to 18 years','do 18 godina',4)
insert into RiskItem values ('from 18 to 60 years','od 18 do 60 godina',4)
insert into RiskItem values ('over 60 years','preko 60 godina',4)
insert into RiskItem values ('Football','Fudbal',5)
insert into RiskItem values ('Basketball','Kosarka',5)
insert into RiskItem values ('Volyball','Odbojka',5)
insert into RiskItem values ('Swimming','Plivanje',5)
insert into RiskItem values ('Tennis','Tenis',5)
insert into RiskItem values ('HandBall','Rukomet',5)
insert into RiskItem values ('Skiing','Skijanje',5)
insert into RiskItem values ('10000 euro','10000 eura',6)
insert into RiskItem values ('30000 euro','30000 eura',6)
insert into RiskItem values ('50000 euro','50000 eura',6)
insert into RiskItem values ('100000 euro','100000 eura',6)
insert into RiskItem values ('Flood','Poplava',10)
insert into RiskItem values ('Theft','Kradja',10)
insert into RiskItem values ('Fire','Pozar',10)
insert into RiskItem values ('Towing','Slepovanje',11)
insert into RiskItem values ('Repair','Popravka',11)
insert into RiskItem values ('Accomodation','Smestaj u hotelu',11)
insert into RiskItem values ('Transport','Alternativni prevoz',11)

