//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merchant.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insurant
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string IdentificationNumber { get; set; }
        public string PassportNumber { get; set; }
        public string Address { get; set; }
        public string TelephoneNumber { get; set; }
        public int InsurancePolicyId { get; set; }
    
        public virtual InsurancePolicy InsurancePolicy { get; set; }
    }
}
