//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merchant.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insurance
    {
        public int Id { get; set; }
        public int RiskCategoryId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> VehicleId { get; set; }
        public Nullable<int> ResidentalBuildingId { get; set; }
        public Nullable<int> VoyageId { get; set; }
        public Nullable<int> InsurancePolicyId { get; set; }
    
        public virtual RiskCategory RiskCategory { get; set; }
        public virtual ResidentalBuilding ResidentalBuilding { get; set; }
        public virtual Vehicle Vehicle { get; set; }
        public virtual InsurancePolicy InsurancePolicy { get; set; }
        public virtual Voyage Voyage { get; set; }
    }
}
