//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merchant.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsurancePolicy
    {
        public int Id { get; set; }
        public decimal Price { get; set; }
        public string OrderId { get; set; }
        public Nullable<int> BuyerId { get; set; }
        public bool IsPaymentSuccessful { get; set; }
    
        public virtual Buyer Buyer { get; set; }
    }
}
