//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merchant.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Buyer> Buyer { get; set; }
        public virtual DbSet<Insurance> Insurance { get; set; }
        public virtual DbSet<InsurancePolicy> InsurancePolicy { get; set; }
        public virtual DbSet<Insurant> Insurant { get; set; }
        public virtual DbSet<Owner> Owner { get; set; }
        public virtual DbSet<Pricelist> Pricelist { get; set; }
        public virtual DbSet<PricelistItem> PricelistItem { get; set; }
        public virtual DbSet<PricelistItems> PricelistItems { get; set; }
        public virtual DbSet<ResidentalBuilding> ResidentalBuilding { get; set; }
        public virtual DbSet<Risk> Risk { get; set; }
        public virtual DbSet<RiskCategory> RiskCategory { get; set; }
        public virtual DbSet<RiskItem> RiskItem { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Vehicle> Vehicle { get; set; }
        public virtual DbSet<Voyage> Voyage { get; set; }
    }
}
