//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merchant.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PricelistItems
    {
        public int Id { get; set; }
        public int PricelistId { get; set; }
    
        public virtual Pricelist Pricelist { get; set; }
    }
}
