//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merchant.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PricelistItem
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public decimal Price { get; set; }
        public int RiskItemId { get; set; }
        public int PricelistItemsId { get; set; }
        public decimal Coefficient { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual PricelistItems PricelistItems { get; set; }
        public virtual RiskItem RiskItem { get; set; }
    }
}
