//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merchant.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResidentalBuilding
    {
        public int Id { get; set; }
        public string Address { get; set; }
        public decimal SurfaceArea { get; set; }
        public decimal BuildingAge { get; set; }
        public decimal EstimatedValue { get; set; }
        public string InsuredFrom { get; set; }
        public int OwnerId { get; set; }
    
        public virtual Owner Owner { get; set; }
    }
}
