//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merchant.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Risk
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Name_Srb { get; set; }
        public int RiskCategoryId { get; set; }
    
        public virtual RiskCategory RiskCategory { get; set; }
    }
}
