//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Merchant.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voyage
    {
        public int Id { get; set; }
        public string Region { get; set; }
        public int NumberOfInsurants { get; set; }
        public int InsurantAge { get; set; }
        public string Sport { get; set; }
        public int InsuredValue { get; set; }
        public int InsurantsId { get; set; }
    
        public virtual Insurants Insurants { get; set; }
    }
}
